#!/bin/bash

wget -O gistic2_BLCA_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.BLCA.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_CESC_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.CESC.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_COADREAD_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.COADREAD.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_COAD_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.COAD.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_UCEC_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.UCEC.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_ESCA_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.ESCA.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_GBM_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.GBM.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_KICH_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.KICH.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_KIRC_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.KIRC.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_KIRP_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.KIRP.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_DLBC_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.DLBC.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_LIHC_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.LIHC.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_LGG_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.LGG.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_GBMLGG_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.GBMLGG.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_LUAD_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.LUAD.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_LUNG_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.LUNG.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_SKCM_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.SKCM.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_MESO_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.MESO.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_UVM_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.UVM.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_OV_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.OV.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_PAAD_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.PAAD.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_PCPG_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.PCPG.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_PRAD_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.PRAD.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_READ_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.READ.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_SARC_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.SARC.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_STAD_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.STAD.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_TGCT_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.TGCT.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_THYM_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.THYM.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_THCA_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.THCA.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
wget -O gistic2_UCS_thresholded.by_genes https://genome-cancer.ucsc.edu/proj/public/xena/download/TCGA/TCGA.UCS.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes
